/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subject = IDL.Record({ 'name' : IDL.Text });
export const TeacherProfile = IDL.Record({
  'subjects' : IDL.Vec(Subject),
  'city' : IDL.Text,
  'name' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'qualifications' : IDL.Text,
  'email' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Variant({ 'teacher' : IDL.Null, 'student' : IDL.Null }),
  'name' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'studentId' : IDL.Principal,
  'subject' : IDL.Text,
  'message' : IDL.Text,
  'teacherId' : IDL.Principal,
});
export const StudentProfile = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'subjectsNeeded' : IDL.Vec(Subject),
  'grade' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'browseTutorsBySubjectAndCity' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(TeacherProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudentInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getTeacherInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getTeacherProfile' : IDL.Func([], [IDL.Opt(TeacherProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerStudent' : IDL.Func([StudentProfile], [], []),
  'registerTeacher' : IDL.Func([TeacherProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendInquiry' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subject = IDL.Record({ 'name' : IDL.Text });
  const TeacherProfile = IDL.Record({
    'subjects' : IDL.Vec(Subject),
    'city' : IDL.Text,
    'name' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'qualifications' : IDL.Text,
    'email' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Variant({ 'teacher' : IDL.Null, 'student' : IDL.Null }),
    'name' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'studentId' : IDL.Principal,
    'subject' : IDL.Text,
    'message' : IDL.Text,
    'teacherId' : IDL.Principal,
  });
  const StudentProfile = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'subjectsNeeded' : IDL.Vec(Subject),
    'grade' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'browseTutorsBySubjectAndCity' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(TeacherProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudentInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getTeacherInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getTeacherProfile' : IDL.Func([], [IDL.Opt(TeacherProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerStudent' : IDL.Func([StudentProfile], [], []),
    'registerTeacher' : IDL.Func([TeacherProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendInquiry' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };