/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'studentId' : Principal,
  'subject' : string,
  'message' : string,
  'teacherId' : Principal,
}
export interface StudentProfile {
  'city' : string,
  'name' : string,
  'email' : string,
  'subjectsNeeded' : Array<Subject>,
  'grade' : string,
  'phoneNumber' : string,
}
export interface Subject { 'name' : string }
export interface TeacherProfile {
  'subjects' : Array<Subject>,
  'city' : string,
  'name' : string,
  'hourlyRate' : bigint,
  'qualifications' : string,
  'email' : string,
  'experienceYears' : bigint,
  'phoneNumber' : string,
}
export interface UserProfile {
  'userType' : { 'teacher' : null } |
    { 'student' : null },
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'browseTutorsBySubjectAndCity' : ActorMethod<
    [string, string],
    Array<TeacherProfile>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStudentInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getTeacherInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getTeacherProfile' : ActorMethod<[], [] | [TeacherProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerStudent' : ActorMethod<[StudentProfile], undefined>,
  'registerTeacher' : ActorMethod<[TeacherProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendInquiry' : ActorMethod<[Principal, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];